CREATE DATABASE Aula09 
GO

USE Aula09 --HABILITA O CONTEXTO - SELECIONA O BD PARA PODER USAR 
GO


CREATE TABLE FUNCIONARIOS (
 ID    INT PRIMARY KEY, 
 Nome  VARCHAR(25), 
 Sexo  CHAR (1), 
 Admissao DATE, 
 Salario DECIMAL (10,2)
 )
 GO

 SET DATEFORMAT DMY
 GO 

 INSERT INTO FUNCIONARIOS (
 ID, 
 Nome, 
 Sexo, 
 Admissao, 
 Salario)

 VALUES (1, 'Maria da Silva', 'F', '10/01/2018', 2500)
 GO

 --SEGUNDO MODO
 INSERT INTO FUNCIONARIOS VALUES (2, 'PEDRO PEREIRA', 'M', '05/03/2000', 990)
 GO

 SELECT *FROM FUNCIONARIOS

 -- INSERE MAIS DADOS NA TABELA 

 INSERT INTO FUNCIONARIOS VALUES 
 (5, 'MARCELO AUGUSTO', 'M', '09/02/2017', 1900.00), 
 (6, 'PEDRO SILVA', 'M', '15/11/2015', 1050.00), 
 (7, 'MONICA DA SILVA', 'F', '12/10/2014', 3000.00)
 GO

--Muda o titulo da coluna
 SELECT ID AS 'CODIGO FUNCIONARIO',
 Nome, 
 Sexo, 
 Salario AS 'Salário'

 FROM FUNCIONARIOS
 GO

 SELECT TOP 3 * FROM FUNCIONARIOS
 GO 

 SELECT TOP 3 
 ID, 
 Nome
 FROM FUNCIONARIOS 
 GO